name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build multi-platform binaries
      run: |
        export VERSION=${{ steps.version.outputs.VERSION }}
        chmod +x build.sh
        ./build.sh
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: Currency Converter API ${{ steps.version.outputs.VERSION }}
        body: |
          ## Currency Converter API ${{ steps.version.outputs.VERSION }}
          
          ### Downloads
          - **Linux (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz`
          - **Windows (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-windows-amd64.zip`
          - **macOS (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz`
          - **macOS (arm64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz`
          
          ### Setup
          1. Download the appropriate binary for your platform
          2. Extract the archive
          3. Copy `.env.example` to `.env` and configure your settings
          4. Run the binary or use the provided start script
          
          ### Authentication
          All API endpoints require Bearer token authentication.
          
          ### Documentation
          See [README.md](https://github.com/rakibhoossain/currency-converter/blob/main/README.md) for full documentation.
        draft: false
        prerelease: false
    
    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/currency-converter-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz
        asset_name: currency-converter-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/currency-converter-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
        asset_name: currency-converter-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
        asset_content_type: application/zip
    
    - name: Upload macOS amd64 Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/currency-converter-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz
        asset_name: currency-converter-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload macOS arm64 Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/currency-converter-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz
        asset_name: currency-converter-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Checksums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain
