name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build multi-platform binaries
      run: |
        export VERSION=${{ steps.version.outputs.VERSION }}
        chmod +x build.sh
        ./build.sh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Currency Converter API ${{ steps.version.outputs.VERSION }}
        body: |
          ## Currency Converter API ${{ steps.version.outputs.VERSION }}

          A Go REST API for currency conversion using OpenExchangeRates with intelligent caching and Bearer token authentication.

          ### 🚀 Quick Start
          1. **Get OpenExchangeRates API Key**: Sign up at [openexchangerates.org](https://openexchangerates.org/signup/free)
          2. **Download** the appropriate binary for your platform below
          3. **Extract** the archive and copy `.env.example` to `.env`
          4. **Configure** your API key and auth token in `.env`
          5. **Run** the binary or use the provided start script

          ### 📦 Downloads
          - **Linux (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz`
          - **Windows (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-windows-amd64.zip`
          - **macOS (amd64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz`
          - **macOS (arm64)**: `currency-converter-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz`

          ### 🔐 Authentication
          All API endpoints require Bearer token authentication.
          Include in header: `Authorization: Bearer your_auth_token_here`

          ### 📋 Features
          - 173+ currencies with real-time rates
          - Smart caching (1-hour rates, 24-hour currencies)
          - Background automatic updates
          - RESTful API with comprehensive error handling
          - Multi-platform binaries ready to run

          ### 📖 Documentation
          See [README.md](https://github.com/rakibhoossain/currency-converter/blob/main/README.md) for full documentation.
        draft: false
        prerelease: false
        files: |
          dist/currency-converter-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz
          dist/currency-converter-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
          dist/currency-converter-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz
          dist/currency-converter-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz
          dist/checksums.txt
